version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    command: [ "postgres", "-c", "log_statement=all" ]

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      # - RUST_BACKTRACE=full
      - RUST_BACKTRACE=1
      - SMTP_HOST=smtp.gmail.com
      - SMTP_USERNAME=yoursmptusername
      - SMTP_PASSWORD=yoursmtppassword
    ports:
      - 8000:8000
    volumes:
      - ./:/app
